Code/Pycharm/Main/server/views/dash_views.py
import copy

import pymysql
from flask import Blueprint, request, render_template, url_for, session, flash
from werkzeug.utils import redirect

from config import DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME, csv_Folder_Path, Category_Kor, Category_Eng, Region_Dict, \
    Category_List_W, Category_radioList_W, Category_List_R, Category_radioList_R, Produce_Num, Weight
from server.define.chart_data import Chartdata_W, Chartdata_R
from server.define.dict import Retail_Dict

bp = Blueprint('dash', __name__, url_prefix='/')

# DB 초기 설정
mydb = pymysql.Connect(host=DB_HOST, user=DB_USERNAME,
                       password=DB_PASSWORD, database=DB_NAME)
cursor = mydb.cursor()

retail_dict = Retail_Dict(DB_USERNAME, DB_HOST, DB_PASSWORD, DB_NAME)
result_dict = retail_dict.RetailDict()


# Dashboard
@bp.route('/dash', methods=('GET', 'POST'))
def board():
    y = request.form.get('region')
    z = request.form.get('category')
    print(y, z)
    return render_template('dash/dash.html')


# Dashboard_도매
@bp.route('/wholesale', methods=('GET', 'POST'))
def wholesale():
    user_nickname = session.get('user_nickname')
    if user_nickname is None:
        flash("로그인이 필요합니다.")
        return redirect(url_for('main.login'))
    else:
        if request.method == 'POST':
            if request.form.get('myRadios'):
                option = request.form.to_dict()['myRadios']
                print('도매: ' + option)
                option = option.split('_')
                category = option[0]  # 카테고리
                dic_set = Category_radioList_W[Category_Kor.index(category)]
                radio_check = copy.deepcopy(dic_set)  # 딕셔너리 깊은 복사
                key_produce = option[1]  # 농산물
                radio_check[key_produce] = ' checked="checked" '

                MyChart = Chartdata_W(DB_USERNAME, DB_HOST, DB_PASSWORD, DB_NAME,
                                      csv_Folder_Path, Category_Kor, Category_List_W, category, key_produce)

                chart = MyChart.Wholesale()

                return render_template('dash/wholesale.html',
                                       category=category, key_produce=key_produce, radio_check=radio_check,
                                       date=chart['1']['date'], price=chart['1']['price'], deal=chart['1']['deal'],
                                       max_price=chart['1']['max_price'], stepSize_price=chart['1']['stepSize_price'],
                                       max_deal=chart['1']['max_deal'], stepSize_deal=chart['1']['stepSize_deal'],
                                       date_f=chart['2']['date_f'], yhat=chart['2']['yhat'],
                                       yhat_l=chart['2']['yhat_l'], yhat_u=chart['2']['yhat_u'],
                                       max_yhat=chart['2']['max_yhat'], stepSize_yhat=chart['2']['stepSize_yhat'],
                                       price_quarter=chart['3']['price_quarter'],
                                       deal_quarter=chart['3']['deal_quarter'],
                                       max_price_quarter=chart['3']['max_price_quarter'],
                                       stepSize_price_quarter=chart['3']['stepSize_price_quarter'],
                                       max_deal_quarter=chart['3']['max_deal_quarter'],
                                       stepSize_deal_quarter=chart['3']['stepSize_deal_quarter'])
            else:
                category = request.form.get('category')
                print('도매: ' + category)
                dic_set = Category_radioList_W[Category_Kor.index(category)]
                radio_check = copy.deepcopy(dic_set)
                keys_list = list(radio_check.keys())
                key_produce = keys_list[0]
                radio_check[key_produce] = ' checked="checked" '

                MyChart = Chartdata_W(DB_USERNAME, DB_HOST, DB_PASSWORD, DB_NAME,
                                      csv_Folder_Path, Category_Kor, Category_List_W, category, key_produce)
                chart = MyChart.Wholesale()

                return render_template('dash/wholesale.html',
                                       category=category, key_produce=key_produce, radio_check=radio_check,
                                       date=chart['1']['date'], price=chart['1']['price'], deal=chart['1']['deal'],
                                       max_price=chart['1']['max_price'], stepSize_price=chart['1']['stepSize_price'],
                                       max_deal=chart['1']['max_deal'], stepSize_deal=chart['1']['stepSize_deal'],
                                       date_f=chart['2']['date_f'], yhat=chart['2']['yhat'],
                                       yhat_l=chart['2']['yhat_l'], yhat_u=chart['2']['yhat_u'],
                                       max_yhat=chart['2']['max_yhat'], stepSize_yhat=chart['2']['stepSize_yhat'],
                                       price_quarter=chart['3']['price_quarter'],
                                       deal_quarter=chart['3']['deal_quarter'],
                                       max_price_quarter=chart['3']['max_price_quarter'],
                                       stepSize_price_quarter=chart['3']['stepSize_price_quarter'],
                                       max_deal_quarter=chart['3']['max_deal_quarter'],
                                       stepSize_deal_quarter=chart['3']['stepSize_deal_quarter'])


# print(result_dict['total']['Vegetable']['M'][20211013])

# Dashboard_소매
@bp.route('/retail', methods=('GET', 'POST'))
def retail():
    user_nickname = session.get('user_nickname')
    if user_nickname is None:
        flash("로그인이 필요합니다.")
        return redirect(url_for('main.login'))
    else:
        if request.method == 'POST':
            if request.form.get('myRadios'):
                option = request.form.to_dict()['myRadios']
                print('소매: ' + option)
                option = option.split('_')
                region = option[0]
                category = option[1]
                dic_set = Category_radioList_R[Category_Kor.index(category)]
                weight = Weight[Category_Kor.index(category)]
                radio_check = copy.deepcopy(dic_set)
                key_produce = option[2]
                radio_check[key_produce] = ' checked="checked" '
                kg = weight[key_produce]

                MyChart = Chartdata_R(result_dict, csv_Folder_Path, Category_Kor, Category_Eng,
                                      Region_Dict, Category_List_R, Produce_Num,
                                      region, category, key_produce)
                chart = MyChart.Retail()

                return render_template('dash/retail.html',
                                       region=region, category=category, key_produce=key_produce,
                                       radio_check=radio_check, date=chart['1']['date'],
                                       result_t=chart['1']['result_t'],
                                       result_t_total=chart['1']['result_t_total'],
                                       yhat_l_T=chart['1']['yhat_l_T'], yhat_u_T=chart['1']['yhat_u_T'],
                                       result_m=chart['2']['result_m'],
                                       result_m_total=chart['2']['result_m_total'],
                                       yhat_l_M=chart['2']['yhat_l_M'], yhat_u_M=chart['2']['yhat_u_M'],
                                       month_List=chart['3']['month_List'],
                                       month_price_T=chart['3']['month_price_T'],
                                       month_price_M=chart['3']['month_price_M'],kg=kg)
            else:
                if request.form.get('selectbox'):
                    sel = request.form.get('selectbox')
                    sel_value = sel.split('_')
                    region = sel_value[0]
                    category = sel_value[1]
                else:
                    region = request.form.get('region')
                    category = request.form.get('category')
                print('소매: ' + region + '_' + category)
                dic_set = Category_radioList_R[Category_Kor.index(category)]
                weight = Weight[Category_Kor.index(category)]
                radio_check = copy.deepcopy(dic_set)
                keys_list = list(radio_check.keys())
                key_produce = keys_list[0]
                radio_check[key_produce] = ' checked="checked" '
                kg = weight[key_produce]

                MyChart = Chartdata_R(result_dict, csv_Folder_Path, Category_Kor, Category_Eng,
                                      Region_Dict, Category_List_R, Produce_Num,
                                      region, category, key_produce)
                chart = MyChart.Retail()

                return render_template('dash/retail.html',
                                       region=region, category=category, key_produce=key_produce,
                                       radio_check=radio_check, date=chart['1']['date'],
                                       result_t=chart['1']['result_t'],
                                       result_t_total=chart['1']['result_t_total'],
                                       yhat_l_T=chart['1']['yhat_l_T'], yhat_u_T=chart['1']['yhat_u_T'],
                                       result_m=chart['2']['result_m'],
                                       result_m_total=chart['2']['result_m_total'],
                                       yhat_l_M=chart['2']['yhat_l_M'], yhat_u_M=chart['2']['yhat_u_M'],
                                       month_List=chart['3']['month_List'],
                                       month_price_T=chart['3']['month_price_T'],
                                       month_price_M=chart['3']['month_price_M'],kg=kg)


# Dashboard_가격비교_소매
@bp.route('/compare2/<category>', methods=('GET', 'POST'))
def compare2(category):
    user_nickname = session.get('user_nickname')
    if user_nickname is None:
        flash("로그인이 필요합니다.")

Code/Pycharm/Main/server/templates/profile/change.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href=" {{ url_for('static', filename='style.css') }} ">

<body class="text-center pt-5">
<main class="container pt-5">
    <form id="contactForm" method="post" class="pt-5" action="{{ url_for('main.change') }}">
        <img class="mb-4" src="{{ url_for('static', filename='img/id.png') }}" alt="" width="72" height="72">
        <h1 class="h3 mb-3 fw-normal">변경할 정보를 입력해주세요.</h1>
        <br>
        <div class="form-floating" style="width: 35%; margin: auto;">
            <input type="nickname" class="form-control" id="nickname" placeholder="nickname" name="nickname"
                   value="{{ user.nickname }}">
            <label for="nickname">별명</label>
        </div>
        <br>
        <div class="form-floating" style="width: 35%; margin: auto;">
            <input type="name" class="form-control" id="name" placeholder="name" name="name" value="{{ user.name }}">
            <label for="name">이름</label>
        </div>
        <br>
        <div class="form-floating" style="width: 35%; margin: auto;">
            <input type="email" class="form-control" id="email" placeholder="email" name="email"
                   value="{{ user.email }}">
            <label for="email">이메일</label>
        </div>
        <br>
        <div class="form-floating" style="width: 35%; margin: auto;">
            <input type="phone" class="form-control" id="phone" placeholder="phone" name="phone"
                   value="{{ user.phone }}">
            <label for="phone">전화번호</label>
        </div>
        <br>
        <button class="w-25 btn btn-lg btn-primary" type="submit" name="profile" value="profile">변경</button>
        <p class="mt-5 mb-3 text-muted">© 2022</p>
    </form>
</main>
</body>

{% endblock %}

Code/Pycharm/Main/server/templates/profile/changepw.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href=" {{ url_for('static', filename='style.css')}} ">

<body class="text-center pt-5">
<main class="container pt-5">
    <form id="contactForm" method="post" class="pt-5" >
        {{ form.csrf_token }}
        <img class="mb-4" src="static/img/id.png" alt="" width="72" height="72">
        <h1 class="h3 mb-3 fw-normal">변경할 비밀번호를 입력해주세요.</h1>

        <div class="form-group" style="width: 50%; margin: auto;">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group" style="width: 50%; margin: auto;">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

        <br>
        <button class="w-25 btn btn-lg btn-primary" type="submit" name="profile" value="profile">변경</button>
        <p class="mt-5 mb-3 text-muted">© 2022</p>
    </form>
</main>
</body>

{% endblock %}

Code/Pycharm/Main/server/templates/profile/confirm.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href=" {{ url_for('static', filename='style.css')}} ">
{% with messages = get_flashed_messages() %}
{% if messages %}
<script>
        alert("{{ messages[-1] }}")
</script>
{% endif %}
{% endwith %}
<body class="text-center pt-5">
<main class="container pt-5">
    <form id="contactForm" action="{{ url_for('main.confirm')}}" method="post" class="pt-5">
        <img class="mb-4" src="static/img/id.png" alt="" width="72" height="72">
        <h1 class="h3 mb-3 fw-normal">비밀번호를 다시 한번 입력해주세요.</h1>

        <br>
        <div class="form-floating" style="width: 35%; margin: auto;">
            <input type="password" class="form-control" id="floatingPassword" placeholder="Password" name="pw">
            <label for="floatingPassword">Password</label>
        </div>
        <br>
        <button class="w-25 btn btn-lg btn-primary" type="submit" name="check" value="{{ choice }}">확인</button>
        <p class="mt-5 mb-3 text-muted">© 2022</p>
    </form>
</main>
</body>

{% endblock %}

Code/Pycharm/Main/server/templates/profile/grade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{{ url_for('static', filename='profile/styles.css') }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato|Quicksand" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

</head>
<script>
    // content, cate, index를 인수로 받아 form 태그로 전송하는 함수
    function goPage1(category = 0) {
        // name이 paging인 태그
        var f = document.paging;

        // form 태그의 하위 태그 값 매개 변수로 대입
        f.category.value = category;

        // input 태그의 값들을 전송하는 주소
        f.action = "{{ url_for('dash.wholesale') }}"

        // 전송 방식 : post
        f.method = "post"
        f.submit();
    };
    </script>
    <script>
    function goPage2(region,category = 0) {
        var f = document.paging;

        f.region.value = region;
        f.category.value = category;

        f.action = "{{ url_for('dash.retail') }}"

        f.method = "post"
        f.submit();
    };
    </script>
<body>


<div class="sel">


<!--<select name="order" >-->
<!--  <select form="myForm" name="select-profession" id="select-profession" >-->
  <select class="" id="wr_28" name="wr_28">
    <option value="" disabled>Profession</option>
    <option value="hacker">Hacker</option>
    <option value="gamer">Gamer</option>
    <option value="developer">Developer</option>
    <option value="programmer">Programmer</option>
    <option value="designer">Designer</option>
  </select>
</div>
<div>
    <form action="" method="get" id="myForm">
    <input type="submit"><br><br>
</form>
    <input type="hidden" name="wr_38" id="wr_38" >

</form>
</div>
<!--<div class="sel sel&#45;&#45;black-panther">-->
<!--  <select form="myForm" name="select-profession" id="select-profession">-->
<!--    <option value="" disabled>분류</option>-->
<!--    <option value="hacker">식량작물</option>-->
<!--    <option value="gamer">특용작물</option>-->
<!--    <option value="developer">채소류</option>-->
<!--    <option value="programmer">과일류</option>-->
<!--  </select>-->
<!--</div>-->
<!--<div>-->
<!--    <form action="" method="get" id="myForm">-->
<!--    <input type="submit">-->
<!--</form>-->


<!--
  <span class="sel__placeholder sel__placeholder--black-panther">Placeholder Text</span>
  <div class="sel__box sel__box--black-panther">
    <span data-option="option_1" class="sel__box__options sel__box__options--black-panther">Option 1</span>
    <span data-option="option_2" class="sel__box__options sel__box__options--black-panther">Option 2</span>
    <span data-option="option_3" class="sel__box__options sel__box__options--black-panther">Option 3</span>
    <span data-option="option_4" class="sel__box__options sel__box__options--black-panther">Option 4</span>
    <span data-option="option_5" class="sel__box__options sel__box__options--black-panther">Option 5</span>
  </div>
-->

<!--
  .not-active.selected = hide
  .active.selected = show
-->
<!--<select id="wr_28" name="wr_28">-->
<!--   <option value="200">200</option>-->
<!--   <option value="300">300</option>-->
<!--   <option value="400">400</option>-->
<!--</select>-->
<!--<input type="hidden" name="wr_38" id="wr_38" >-->
<script>
$(function(){
  $("#select-profession").change(function() {
     $("#select-profession2").val($(this).val());
     ad_calcs1();
  });
});
function ad_calcs1() {
	alert(1);
}
$(function(){
  $("#wr_28").change(function() {
     $("#wr_38").val($(this).val());
     ad_calcs1();
  });
});
function ad_calcs1() {
	alert(1);
}
</script>

<!--<hr class="rule">-->

<!--<div class="sel sel&#45;&#45;superman">-->
<!--  <select name="select-superpower" id="select-superpower">-->
<!--    <option value="" disabled>Superpower</option>-->
<!--    <option value="hacker">Power</option>-->
<!--    <option value="gamer">Speed</option>-->
<!--    <option value="developer">Acrobatics</option>-->
<!--    <option value="programmer">Accuracy</option>-->
<!--  </select>-->
<!--</div>-->

<!--
  <span class="sel__placeholder sel__placeholder--black-panther">Placeholder Text</span>
  <div class="sel__box sel__box--black-panther">
    <span data-option="option_1" class="sel__box__options sel__box__options--black-panther">Option 1</span>
    <span data-option="option_2" class="sel__box__options sel__box__options--black-panther">Option 2</span>
    <span data-option="option_3" class="sel__box__options sel__box__options--black-panther">Option 3</span>
    <span data-option="option_4" class="sel__box__options sel__box__options--black-panther">Option 4</span>
    <span data-option="option_5" class="sel__box__options sel__box__options--black-panther">Option 5</span>
  </div>
-->

<!--
  .not-active.selected = hide
  .active.selected = show
-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
<script src="{{ url_for('static', filename='profile/scripts.js')}}"></script>
</body>
</html>

Code/Pycharm/Main/server/templates/profile/seller.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Code/Pycharm/Main/server/templates/profile/team.html
{% extends 'base.html' %}

{% block content %}

<!-- Team -->
<section class="page-section bg-light" id="team">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading text-uppercase">Our Amazing Team</h2>
            <h3 class="section-subheading text-muted">빅데이터 분석을 활용한 인공지능 기반 디지털트랜스포메이션 [3회차] 1조</h3>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="static/img/team/1.png" alt="...">
                    <h4>김용석</h4>
                    <p class="text-muted">Lead Designer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile">
                        <svg class="svg-inline--fa fa-twitter" aria-hidden="true" focusable="false" data-prefix="fab"
                             data-icon="twitter" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"
                             data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M459.4 151.7c.325 4.548 .325 9.097 .325 13.65 0 138.7-105.6 298.6-298.6 298.6-59.45 0-114.7-17.22-161.1-47.11 8.447 .974 16.57 1.299 25.34 1.299 49.06 0 94.21-16.57 130.3-44.83-46.13-.975-84.79-31.19-98.11-72.77 6.498 .974 12.99 1.624 19.82 1.624 9.421 0 18.84-1.3 27.61-3.573-48.08-9.747-84.14-51.98-84.14-102.1v-1.299c13.97 7.797 30.21 12.67 47.43 13.32-28.26-18.84-46.78-51.01-46.78-87.39 0-19.49 5.197-37.36 14.29-52.95 51.65 63.67 129.3 105.3 216.4 109.8-1.624-7.797-2.599-15.92-2.599-24.04 0-57.83 46.78-104.9 104.9-104.9 30.21 0 57.5 12.67 76.67 33.14 23.72-4.548 46.46-13.32 66.6-25.34-7.798 24.37-24.37 44.83-46.13 57.83 21.12-2.273 41.58-8.122 60.43-16.24-14.29 20.79-32.16 39.31-52.63 54.25z"></path>
                        </svg><!-- <i class="fab fa-twitter"></i> Font Awesome fontawesome.com --></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile">
                        <svg class="svg-inline--fa fa-facebook-f" aria-hidden="true" focusable="false" data-prefix="fab"
                             data-icon="facebook-f" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"
                             data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M279.1 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.4 0 225.4 0c-73.22 0-121.1 44.38-121.1 124.7v70.62H22.89V288h81.39v224h100.2V288z"></path>
                        </svg><!-- <i class="fab fa-facebook-f"></i> Font Awesome fontawesome.com --></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile">
                        <svg class="svg-inline--fa fa-linkedin-in" aria-hidden="true" focusable="false"
                             data-prefix="fab" data-icon="linkedin-in" role="img" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 448 512" data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M100.3 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.6 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.3 61.9 111.3 142.3V448z"></path>
                        </svg><!-- <i class="fab fa-linkedin-in"></i> Font Awesome fontawesome.com --></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="static/img/team/2.png" alt="...">
                    <h4>손명준</h4>
                    <p class="text-muted">Lead Marketer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile">
                        <svg class="svg-inline--fa fa-linkedin-in" aria-hidden="true" focusable="false"
                             data-prefix="fab" data-icon="linkedin-in" role="img" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 448 512" data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M100.3 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.6 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.3 61.9 111.3 142.3V448z"></path>
                        </svg><!-- <i class="fab fa-linkedin-in"></i> Font Awesome fontawesome.com --></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="static/img/team/3.png" alt="...">
                    <h4>우병길</h4>
                    <p class="text-muted">Lead Marketer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile">
                        <svg class="svg-inline--fa fa-linkedin-in" aria-hidden="true" focusable="false"
                             data-prefix="fab" data-icon="linkedin-in" role="img" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 448 512" data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M100.3 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.6 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.3 61.9 111.3 142.3V448z"></path>
                        </svg><!-- <i class="fab fa-linkedin-in"></i> Font Awesome fontawesome.com --></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="static/img/team/4.png" alt="...">
                    <h4>최형기</h4>
                    <p class="text-muted">Lead Developer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker github Profile">
                        <svg class="svg-inline--fa fa-github" aria-hidden="true" focusable="false" data-prefix="fab"
                             data-icon="github" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"
                             data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M100.3 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.6 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.3 61.9 111.3 142.3V448z"></path>
                        </svg><!-- <i class="fab fa-linkedin-in"></i> Font Awesome fontawesome.com --></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="team-member">
                    <img class="mx-auto rounded-circle" src="static/img/team/5.png" alt="...">
                    <h4>홍석현</h4>
                    <p class="text-muted">Lead Developer</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile">
                        <svg class="svg-inline--fa fa-linkedin-in" aria-hidden="true" focusable="false"
                             data-prefix="fab" data-icon="linkedin-in" role="img" xmlns="http://www.w3.org/2000/svg"
                             viewBox="0 0 448 512" data-fa-i2svg="">
                            <path fill="currentColor"
                                  d="M100.3 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.6 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.3 61.9 111.3 142.3V448z"></path>
                        </svg><!-- <i class="fab fa-linkedin-in"></i> Font Awesome fontawesome.com --></a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto text-center"><p class="large text-muted">Lorem ipsum dolor sit amet,
                consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam
                corporis ea, alias ut unde.</p></div>
        </div>
    </div>
</section>

{% endblock %}